- name: Install Apache
  ansible.builtin.package:
    name: httpd
    state: present

- name: Start and enable Apache
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

- name: Create index.html
  ansible.builtin.copy:
    dest: /var/www/html/index.html
    content: "<h1>Hello from Web Server {{ inventory_hostname }}</h1>"
    mode: '0644'
