- name: Install Apache (Debian/Ubuntu)
  ansible.builtin.apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"

- name: Install Apache (RedHat/CentOS/Amazon Linux with yum)
  ansible.builtin.yum:
    name: httpd
    state: present
  when: (ansible_os_family == "RedHat" or ansible_distribution == "Amazon") and ansible_pkg_mgr == "yum"

- name: Install Apache (RedHat/CentOS/Amazon Linux with dnf)
  ansible.builtin.dnf:
    name: httpd
    state: present
    use_backend: dnf4
  when: (ansible_os_family == "RedHat" or ansible_distribution == "Amazon") and ansible_pkg_mgr == "dnf"

- name: Start and enable Apache (Debian/Ubuntu)
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
  when: ansible_os_family == "Debian"

- name: Start and enable Apache (RedHat/CentOS/Amazon Linux)
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
  when: ansible_os_family == "RedHat" or ansible_distribution == "Amazon"

- name: Create index.html
  ansible.builtin.copy:
    dest: /var/www/html/index.html
    content: "<h1>Hello from Web Server {{ inventory_hostname }}</h1>"
    mode: '0644'
