- name: Update and upgrade apt packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Install common packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - git
      - curl
    state: present
  when: ansible_os_family == "Debian"

- name: Install common packages (RedHat/CentOS/Amazon Linux with yum)
  ansible.builtin.yum:
    name:
      - git
      - curl
    state: present
  when: (ansible_os_family == "RedHat" or ansible_distribution == "Amazon") and ansible_pkg_mgr == "yum"

- name: Install common packages (RedHat/CentOS/Amazon Linux with dnf)
  ansible.builtin.dnf:
    name:
      - git
      - curl
    state: present
    use_backend: dnf4
  when: (ansible_os_family == "RedHat" or ansible_distribution == "Amazon") and ansible_pkg_mgr == "dnf"
